#!/usr/bin/env python3
"""
Omnicrawl Outreach Engine v2
Queries the target_bravo PostgreSQL database for contractors with valid, unclaimed emails,
generates a custom Window Sticker QR Code pointing to their profile, renders personalized B2B
emails via Jinja2 offline templates using operational_matrix data, and updates tracking columns in DB.
"""

import os
import re
import json
import psycopg2
from jinja2 import Template
import qrcode

# Define directories relative to this script
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Jinja2 Email Template
EMAIL_TEMPLATE = """Subject: Your new {{ category }} profile on the {{ city }} Local Directory

Hi {{ name }} team,

We recently upgraded our {{ city }} professional directory and featured your business in the {{ category }} section based on your local metrics.

We have generated a live verification link for your business profile. You can view it and claim ownership here:
Verification Link: {{ profile_url }}

=== Competitive Gap Analysis ===
{% if gaps -%}
Our market research indicates some clear conversion gaps compared to the top-performing {{ category }} contractors in {{ city }}:
{% for gap in gaps -%}
- Our data shows that {{ gap.percentage }}% of top-performing contractors in {{ city }} offer {{ gap.name }}. You are currently missing this, which is a major signal for high-intent customers.
{% endfor -%}
By claiming your profile and adding these missing certifications, our dispatch engine will be able to route urgent leads to you automatically.
{%- else -%}
Your listing highlights your premium qualifications, licensing status, and verified local presence to help you stand out against your competitors.
{%- endif %}

We have also generated a custom physical Window Sticker QR code for your business, bridging the offline-to-online gap so your physical customers can instantly scan and view your L&I verified status. (We've saved this locally as {{ qr_code_filename }}).

Claiming your listing is free and allows you to update your contact info and receive direct leads.

Best,
The {{ city }} Directory Team

---
This analysis was generated by the Onnicrawl Dispatch Engine based on live market data.
"""

CAPABILITY_NAMES = {
    "has_24_7_emergency": "24/7 Emergency Service",
    "offers_financing": "Financing Options",
    "offers_free_estimates": "Free Estimates",
    "is_family_owned": "Family-Owned Operations",
    "eco_friendly_practices": "Eco-Friendly Practices",
    "handles_septic": "Septic System Operations",
    "heat_pump_specialist": "Heat Pump Specialization",
    "cabinet_refacing": "Cabinet Refacing",
    "serves_residential": "Residential Services",
    "serves_commercial": "Commercial Services",
    "explicit_warranties_mentioned": "Explicit Warranties / Guarantees"
}

def extract_matrix_capabilities(matrix):
    if not matrix:
        return {}
    if isinstance(matrix, str):
        try:
            matrix = json.loads(matrix)
        except Exception:
            return {}
            
    core = matrix.get("core_features", {})
    niche = matrix.get("niche_features", {})
    comm = matrix.get("commercial_focus", {})
    trust = matrix.get("trust_signals", {})
    
    return {
        "has_24_7_emergency": core.get("has_24_7_emergency", False),
        "offers_financing": core.get("offers_financing", False),
        "offers_free_estimates": core.get("offers_free_estimates", False),
        "is_family_owned": core.get("is_family_owned", False),
        "eco_friendly_practices": core.get("eco_friendly_practices", False),
        "handles_septic": niche.get("handles_septic", False),
        "heat_pump_specialist": niche.get("heat_pump_specialist", False),
        "cabinet_refacing": niche.get("cabinet_refacing", False),
        "serves_residential": comm.get("serves_residential", True),
        "serves_commercial": comm.get("serves_commercial", False),
        "explicit_warranties_mentioned": trust.get("explicit_warranties_mentioned", False)
    }

def load_markets_config():
    """
    Attempts to read market.toml from various directories.
    Supports tomllib (Python 3.11+), third-party toml, or falls back to a simple regex parser.
    """
    config_paths = [
        os.path.join(SCRIPT_DIR, "market.toml"),
        os.path.join(os.path.dirname(SCRIPT_DIR), "market.toml"),
        os.path.join(SCRIPT_DIR, "target_bravo", "market.toml"),
    ]
    
    markets = []
    
    for path in config_paths:
        if os.path.exists(path):
            try:
                # 1. Try python 3.11+ tomllib
                try:
                    import tomllib
                    with open(path, "rb") as f:
                        toml_data = tomllib.load(f)
                        if "markets" in toml_data:
                            print(f"[Outreach Engine] Loaded markets from {path} via tomllib")
                            return toml_data["markets"]
                except ImportError:
                    pass
                
                # 2. Try third-party toml package
                try:
                    import toml
                    with open(path, "r", encoding="utf-8") as f:
                        toml_data = toml.load(f)
                        if "markets" in toml_data:
                            print(f"[Outreach Engine] Loaded markets from {path} via toml package")
                            return toml_data["markets"]
                except ImportError:
                    pass
                
                # 3. Simple fallback parser for array of tables [[markets]]
                with open(path, "r", encoding="utf-8") as f:
                    current_market = None
                    for line in f:
                        line = line.strip()
                        if not line or line.startswith("#"):
                            continue
                        if line == "[[markets]]":
                            if current_market:
                                markets.append(current_market)
                            current_market = {}
                            continue
                        if "=" in line and current_market is not None:
                            k, v = line.split("=", 1)
                            k = k.strip()
                            v = v.strip().strip('"').strip("'")
                            if v.startswith("[") and v.endswith("]"):
                                v = [x.strip().strip('"').strip("'") for x in v[1:-1].split(",") if x.strip()]
                            current_market[k] = v
                    if current_market:
                        markets.append(current_market)
                if markets:
                    print(f"[Outreach Engine] Loaded {len(markets)} markets from {path} via fallback parser")
                    return markets
            except Exception as e:
                print(f"[Outreach Engine Warning] Error parsing {path}: {e}")
                
    print("[Outreach Engine] Using default configuration values.")
    return [{
        "target_city": "Vancouver",
        "target_state": "WA",
        "network_domain": "vancouver.aiyoda.com",
    }, {
        "target_city": "Portland",
        "target_state": "OR",
        "network_domain": "portland.aiyoda.com",
    }]

def generate_slug(name):
    """Replicates the Rust compiler slug generation logic in Python."""
    slug = name.lower()
    slug = re.sub(r'[^a-z0-9]+', '-', slug)
    slug = '-'.join([s for s in slug.split('-') if s])
    return slug

def get_nice_category(category):
    """Translates database category slugs to reader-friendly professional terms."""
    mapping = {
        "plumbing": "plumbing",
        "electrical": "electrical",
        "hvac": "HVAC",
        "kitchen_remodel": "kitchen remodeling",
        "septic_system": "septic system",
        "pest_control": "pest control",
    }
    return mapping.get(category, category)

def main():
    db_url = os.environ.get("DATABASE_URL", "postgres://postgres:password@localhost:5432/postgres")
    
    markets = load_markets_config()
    markets_by_city = {m["target_city"].lower(): m for m in markets}
    
    print(f"[Outreach Engine] Connecting to PostgreSQL database...")
    try:
        conn = psycopg2.connect(db_url)
        cursor = conn.cursor()
    except Exception as e:
        print(f"[Outreach Engine Error] Failed to connect to PostgreSQL: {e}")
        return
    
    try:
        # Fetch contractors - [DRY RUN PATCH] Temporarily select all contractors regardless of outreach_status
        cursor.execute(
            "SELECT id, legal_entity_name, service_category, enriched_data, target_city, operational_matrix "
            "FROM contractors"
        )
        rows = cursor.fetchall()
    except Exception as e:
        print(f"[Outreach Engine Error] Failed to read contractors table: {e}")
        conn.close()
        return

    # Cache benchmark contractors for comparative gap analysis
    print("[Outreach Engine] Fetching benchmark contractors for comparative analysis...")
    top_contractors_by_group = {}
    try:
        cursor.execute(
            "SELECT id, service_category, target_city, operational_matrix, enriched_data "
            "FROM contractors "
            "WHERE lifecycle_state >= 2"
        )
        benchmark_rows = cursor.fetchall()
        
        benchmarks_by_group = {}
        for b_row in benchmark_rows:
            b_id, b_cat, b_city, b_matrix, b_enriched = b_row
            
            b_score = 0
            if b_enriched:
                try:
                    if isinstance(b_enriched, str):
                        b_enriched_dict = json.loads(b_enriched)
                    else:
                        b_enriched_dict = b_enriched
                    b_score = b_enriched_dict.get("monetization_score", 0)
                except Exception:
                    pass
                    
            b_matrix_dict = {}
            if b_matrix:
                try:
                    if isinstance(b_matrix, str):
                        b_matrix_dict = json.loads(b_matrix)
                    else:
                        b_matrix_dict = b_matrix
                except Exception:
                    pass
                    
            key = (b_cat, b_city)
            if key not in benchmarks_by_group:
                benchmarks_by_group[key] = []
            benchmarks_by_group[key].append({
                "id": b_id,
                "monetization_score": b_score,
                "matrix": b_matrix_dict
            })
            
        for key, list_of_contractors in benchmarks_by_group.items():
            list_of_contractors.sort(key=lambda x: x["monetization_score"], reverse=True)
            top_contractors_by_group[key] = list_of_contractors[:3]
            
        print(f"[Outreach Engine] Cached benchmarks for {len(top_contractors_by_group)} category/city combinations.")
    except Exception as e:
        print(f"[Outreach Engine Warning] Failed to fetch benchmark contractors: {e}")

    print(f"[Outreach Engine] Found {len(rows)} contractors to process.")
    drafts = []
    
    # Compile the Jinja2 template
    template = Template(EMAIL_TEMPLATE)
    
    for row in rows:
        contractor_id, name, service_category, enriched_data_str, target_city, operational_matrix = row
        
        email = None
        claimed = False
        
        if enriched_data_str:
            try:
                if isinstance(enriched_data_str, dict):
                    enriched = enriched_data_str
                else:
                    enriched = json.loads(enriched_data_str)
                email = enriched.get("email")
                claimed = enriched.get("claimed", False)
            except Exception as e:
                print(f"[Outreach Engine Warning] Failed to parse enriched_data JSON: {e}")
                pass
                
        nice_category = get_nice_category(service_category)
        slug = generate_slug(name)

        # Validate email exists, is not empty, and claimed status is False
        # [DRY RUN PATCH] Fallback placeholder email for testing if missing
        if not email or not isinstance(email, str) or not email.strip():
            email = f"info@{slug}.com"
            
        # [DRY RUN PATCH] Temporarily ignore claimed status during testing phase
        # if claimed:
        #     continue
            
        email = email.strip()
        
        # Look up config details based on target_city
        city_lower = target_city.lower() if target_city else "vancouver"
        m_config = markets_by_city.get(city_lower, {})
        city = m_config.get("target_city", target_city or "Vancouver")
        domain = m_config.get("network_domain", f"{city.lower()}.aiyoda.com")
        
        # Highlight verification link matching compiler.rs exactly in dist/
        city_slug = generate_slug(city)
        niche_slug = generate_slug(service_category)
        profile_url = f"https://{domain}/{city_slug}/{niche_slug}/{slug}/"
        
        # Extract operational matrix properties and perform gap analysis
        target_caps = extract_matrix_capabilities(operational_matrix)
        
        # Determine gaps
        benchmarks = top_contractors_by_group.get((service_category, target_city), [])
        competitors = [b for b in benchmarks if b["id"] != contractor_id]
        competitor_caps_list = [extract_matrix_capabilities(c["matrix"]) for c in competitors]
        num_competitors = len(competitors)
        
        gaps = []
        if num_competitors > 0:
            for cap_key, friendly_name in CAPABILITY_NAMES.items():
                # Apply niche-specific capability restrictions
                if cap_key == "cabinet_refacing" and service_category != "kitchen_remodel":
                    continue
                if cap_key == "handles_septic" and service_category != "septic_system":
                    continue
                if cap_key == "heat_pump_specialist" and service_category != "hvac":
                    continue
                    
                target_has_it = target_caps.get(cap_key, False)
                comp_count = sum(1 for c_cap in competitor_caps_list if c_cap.get(cap_key, False))
                
                # Gap exists if target lacks it and >= 50% of competitors have it
                if not target_has_it and comp_count > 0:
                    pct = int((comp_count / num_competitors) * 100)
                    if pct >= 50:
                        gaps.append({
                            "key": cap_key,
                            "name": friendly_name,
                            "percentage": pct
                        })
        
        # Generate Window Sticker QR Code (PNG)
        qrcodes_dir = os.path.join(SCRIPT_DIR, "outreach_qrcodes")
        os.makedirs(qrcodes_dir, exist_ok=True)
        qr_filename = f"{slug}_qr.png"
        qr_path = os.path.join(qrcodes_dir, qr_filename)
        
        try:
            qr = qrcode.QRCode(version=1, box_size=10, border=4)
            qr.add_data(profile_url)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            img.save(qr_path)
        except Exception as e:
            print(f"[Outreach Engine Warning] Failed to generate QR Code for {name}: {e}")
            qr_filename = "[Error generating QR Code]"

        # Render email body with Jinja2 template
        rendered_body = template.render(
            name=name,
            city=city,
            category=nice_category,
            profile_url=profile_url,
            gaps=gaps,
            qr_code_filename=qr_filename
        )
        
        # Parse subject from template body output
        subject = f"Your new {nice_category} profile on the {city} Local Directory"
        body_content = rendered_body
        if rendered_body.startswith("Subject:"):
            lines = rendered_body.split("\n", 1)
            subject = lines[0].replace("Subject:", "").strip()
            body_content = lines[1].strip() if len(lines) > 1 else ""

        drafts.append({
            "to": email,
            "subject": subject,
            "body": body_content
        })
        
        if len(drafts) >= 10:  # [DRY RUN PATCH] Limit to 10 drafts for review during testing
            break
        
        # Update PostgreSQL database to track outreach status
        # [DRY RUN PATCH] Temporarily disabled to prevent DB pollution during dry run testing
        # try:
        #     cursor.execute(
        #         "UPDATE contractors "
        #         "SET outreach_status = 'sent', last_outreached_at = CURRENT_TIMESTAMP "
        #         "WHERE id = %s",
        #         (contractor_id,)
        #     )
        # except Exception as e:
        #     print(f"[Outreach Engine Warning] Failed to update PostgreSQL tracking for {name}: {e}")
        #     pass

    # Commit the database changes
    try:
        conn.commit()
    except Exception as e:
        print(f"[Outreach Engine Error] Failed to commit Postgres updates: {e}")
        pass
        
    dry_run_path = os.path.join(SCRIPT_DIR, "outreach_dry_run_v2.txt")
    try:
        with open(dry_run_path, "w", encoding="utf-8") as f:
            for i, draft in enumerate(drafts, 1):
                f.write(f"=== Draft #{i} ===\n")
                f.write(f"To: {draft['to']}\n")
                f.write(f"Subject: {draft['subject']}\n")
                f.write(f"Body:\n{draft['body']}\n")
                f.write("=" * 40 + "\n\n")
        
        print(f"\n[Outreach Engine Success] Successfully drafted {len(drafts)} outreach emails.")
        print(f"[Outreach Engine Success] Generated outreach logs saved to: {dry_run_path}")
    except Exception as e:
        print(f"[Outreach Engine Error] Failed to write dry run file: {e}")
        
    conn.close()

if __name__ == "__main__":
    main()
